[package]
name = "tcnet-rs"
version = "0.1.0"
edition = "2024"
authors = ["Julius Schmitt dev@jsch.in"]

[lib]
name = "tcnet"
path = "src/lib.rs"

[[bin]]
name = "tcnet_test_node"
path = "src/main.rs"

[[bin]]
name = "simulator"
path = "src/bin/simulator.rs"
required-features = ["simulator"]

[[bin]]
name = "viewer"
path = "src/bin/viewer.rs"
required-features = ["viewer"]

[features]
simulator = ["dep:eframe", "dep:egui", "dep:rodio", "dep:lofty"]
viewer = ["dep:eframe", "dep:egui"]

[dependencies]
bitflags = "2.11.0"
deku = "0.20.3"
tokio = { version = "1.49.0", features = ["time", "net", "sync", "rt-multi-thread", "tracing", "macros"] }
log = "0.4.29"
env_logger = "0.11.9"
clap = { version = "4.5.60", features = ["derive"] }
getifs = "0.4.0"
kanal = "0.1.1"
triple_buffer = "9"
eframe = { version = "0.31", optional = true, features = ["wgpu"] }
egui = { version = "0.31", optional = true }
rodio = { version = "0.20", optional = true, features = ["symphonia-all"] }
lofty = { version = "0.22", optional = true }
