[package]
name = "tcnet-rs"
version = "0.1.0"
edition = "2024"
authors = ["Julius Schmitt dev@jsch.in"]

[lib]
name = "tcnet"
path = "src/lib.rs"

[[bin]]
name = "tcnet_test_node"
path = "src/main.rs"

[dependencies]
bitflags = "2.11.0"
deku = "0.20.3"
tokio = { version = "1.49.0", features = ["time", "net", "sync", "rt-multi-thread", "tracing"] }
log = "0.4.29"
env_logger = "0.11.9"
clap = { version = "4.5.60", features = ["derive"] }
getifs = "0.4.0"
kanal = "0.1.1"